name = "argusai"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.development]
name = "argusai-dev"
[env.development.observability]
enabled = true
[env.development.vars]
ENVIRONMENT = "development"
GITHUB_APP_ID = "1454778"
GITHUB_MODEL = "gpt-4o-mini"
LOG_LEVEL = "debug"

# Production environment
[env.production]
name = "argusai"
routes = [
  { pattern = "api.argusai.dev/*", zone_name = "argusai.dev" }
]
[env.production.vars]
ENVIRONMENT = "production"
GITHUB_APP_ID = "your-prod-app-id"
GITHUB_MODEL = "gpt-4o"
LOG_LEVEL = "info"

# KV Namespaces (create with: wrangler kv:namespace create "NAME")
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "df70afec18184e6da7a50bad00cbae45"

[[env.production.kv_namespaces]]
binding = "RATE_LIMITS"
id = "3f9fae87dddd4751823a13ce49dfa81c"

[[env.production.kv_namespaces]]
binding = "CONFIG"
id = "6155db907791462998569c559e71a8cd"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "13021ce160594c9bb2582e976da7a2cc"

[[env.development.kv_namespaces]]
binding = "RATE_LIMITS"
id = "06264102637f40a6a366b0cf6b45b2d5"

[[env.development.kv_namespaces]]
binding = "CONFIG"
id = "f28a375dc99b45c8905e0d7016544a13"

# Free Tier: No queues needed
# Processing happens directly in webhook handler using event.waitUntil()

# R2 bucket for batch log storage (optional)
# Free tier: Use console.log() and wrangler tail for logging
# [[r2_buckets]]
# binding = "LOG_STORAGE"
# bucket_name = "argusai-logs"

# Service bindings (if using separate workers)
# [[services]]
# binding = "AUTH_SERVICE"
# service = "argusai-auth"
# environment = "production"

# Durable Objects (for advanced rate limiting)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"
# script_name = "argusai"

# Secrets (set with: wrangler secret put SECRET_NAME)
# Required secrets:
# - GITHUB_APP_PRIVATE_KEY: GitHub App private key for authentication
# - GITHUB_WEBHOOK_SECRET: Secret for validating webhook signatures
# - GITHUB_TOKEN: GitHub PAT with models:read permission
# Optional secrets:
# - SENTRY_DSN: For error tracking
# - SLACK_WEBHOOK_URL: For notifications

# Performance settings
[env.production.performance]
cpu_ms = 50  # Limit CPU time per request

# Logpush configuration for better log collection
# Note: Logpush requires enterprise plan
# For free tier, use wrangler tail for real-time logs
